name: Deploy Backend to Server

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Pull latest changes from main
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no waterindex@192.168.3.245 "cd G:/Project/bagas-auto-deploy && git pull origin main"
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
